language: java
install:
  - wget https://github.com/validator/validator/releases/download/18.11.5/vnu.jar_18.11.5.zip
  - unzip -j vnu.jar_18.11.5.zip dist/vnu.jar

script: 
  #HTML tests
  - java -jar vnu.jar --html $(find . -name "*.html" |grep -i -v "exercice-13")
  #CSS tests
  - java -jar vnu.jar --css $(find . -name "*.css")
